-- Création de la base de données
-- CREATE DATABASE eshop;

-- Utilisation de la base de données
-- USE eshop;

-- Création de la table Client
CREATE TABLE client (
    CLI_ID SERIAL,
    CLI_NOM VARCHAR(100) NOT NULL,
    CLI_PRENOM VARCHAR(100) NOT NULL,
    CLI_AGE INT NOT NULL DEFAULT 0,
    CLI_ADRESSE VARCHAR(250) NULL,
    CLI_EMAIL VARCHAR(100) NOT NULL,
    CLI_PASSWORD VARCHAR(250) NULL,
    CLI_POIDS INT NOT NULL DEFAULT 0,
    CLI_CELIBATAIRE BOOLEAN NOT NULL DEFAULT FALSE,
    CLI_NUMERO_TELEPHONE VARCHAR(20) NULL,
    CLI_COORDONNEES_BANCAIRE VARCHAR(200) NULL,
    CLI_SEXE INT NOT NULL DEFAULT 0,
    CLI_NOMBRE_ARTICLES_ACHETES INT NOT NULL DEFAULT 0,
    CLI_NOMBRE_COMMENTAIRES INT NOT NULL DEFAULT 0,
    CLI_TOTAL_DEPENSES DECIMAL(10, 2) NOT NULL DEFAULT 0
);


-- Création de la table Produit
CREATE TABLE produit (
    PRO_ID SERIAL,
    PRO_NOM VARCHAR(150) NOT NULL,
    PRO_REFERENCE VARCHAR(100) NOT NULL,
    PRO_STOCK INT NOT NULL DEFAULT 0,
    PRO_PRIX_ACHAT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PRO_PRIX_VENTE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PRO_TYPE INT NOT NULL DEFAULT 0,
    PRO_COULEUR VARCHAR(20) NULL,
    PRO_MODELE VARCHAR(100) NOT NULL,
    PRO_SAV BOOLEAN NOT NULL DEFAULT FALSE,
    PRO_NOTE INT NOT NULL DEFAULT 0,
    PRO_POIDS INT NOT NULL DEFAULT 0,
    PRO_MARQUE VARCHAR(100) NULL,
    PRO_DIMENTIONS VARCHAR(50) NULL,
    PRO_NOMBRE_RETOURS INT NOT NULL DEFAULT 0,
    PRO_FDP DECIMAL(6, 2) NOT NULL DEFAULT 0,
    PRO_DESCRIPTION TEXT NULL,
    PRO_FOURNISSEUR_ID INT NOT NULL
);



-- Ajout de la contrainte Clé Primaire sur la table "client"
ALTER TABLE client
	ADD CONSTRAINT PK_Client PRIMARY KEY (CLI_ID);

-- Ajout de la contrainte Clé Primaire sur la table "produit"
ALTER TABLE produit 
	ADD CONSTRAINT PK_Produit PRIMARY KEY (PRO_ID);




-- Création de la table Fournisseur
CREATE TABLE fournisseur (
    FOU_ID SERIAL,
    FOU_NOM VARCHAR(100) NOT NULL,
    FOU_ADRESSE VARCHAR(250) NULL,
    FOU_NUMERO_TELEPHONE VARCHAR(20) NULL,
    FOU_RIB VARCHAR(200) NULL,
    FOU_RESPONSABLE VARCHAR(200) NOT NULL,
    PRIMARY KEY (FOU_ID)
);


-- Création de la table Commande
CREATE TABLE commande (
    CMD_ID SERIAL,
    CMD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CMD_ETAT INT NOT NULL DEFAULT 0,
    CMD_QUANTITE INT NOT NULL DEFAULT 1,
    CMD_CLIENT_ID INT NOT NULL,
    PRIMARY KEY (CMD_ID)
);


-- Création de la table Achat
CREATE TABLE achat (
    ACH_ID SERIAL,
    ACH_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACH_MONTANT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ACH_QUANTITE INT NOT NULL DEFAULT 0,
    ACH_PROMO BOOLEAN NOT NULL DEFAULT FALSE,
    ACH_COMMANDE_ID INT NOT NULL,
    ACH_PRODUIT_ID INT NOT NULL,
    PRIMARY KEY (ACH_ID)
);


-- Création de la table Promotion
CREATE TABLE promotion (
    PMT_ID SERIAL,
    PMT_NOM VARCHAR(50) NOT NULL,
    PMT_MONTANT DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PMT_DATE_DEBUT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PMT_DATE_FIN TIMESTAMP NULL,
    PMT_NOMBRE_VENTES INT NOT NULL DEFAULT 0,
    PMT_PRODUIT_ID INT NOT NULL,
    PRIMARY KEY (PMT_ID)
);


-- Création de la table Commentaire
CREATE TABLE commentaire (
    COM_ID SERIAL,
    COM_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COM_NOTE INT NOT NULL DEFAULT 0,
    COM_COMMENTAIRE TEXT NOT NULL,
    COM_PRODUIT_ID INT NULL,
    COM_CLIENT_ID INT NOT NULL,
    PRIMARY KEY (COM_ID)
);






-- Clés étrangères Produit -> Fournisseur
ALTER TABLE produit
    ADD
        CONSTRAINT FK_ProduitFournisseur
        FOREIGN KEY (PRO_FOURNISSEUR_ID)
        REFERENCES fournisseur(FOU_ID);


-- Clés étrangères Commande -> Client
ALTER TABLE commande
    ADD CONSTRAINT FK_CommandeClient
        FOREIGN KEY (CMD_CLIENT_ID)
        REFERENCES client(CLI_ID);


-- Clés étrangères Achat -> Produit
ALTER TABLE achat
    ADD CONSTRAINT FK_AchatProduit
        FOREIGN KEY (ACH_PRODUIT_ID)
        REFERENCES produit(PRO_ID);


-- Clés étrangères Achat -> Commande
ALTER TABLE achat
    ADD CONSTRAINT FK_AchatCommande
        FOREIGN KEY (ACH_COMMANDE_ID)
        REFERENCES commande(CMD_ID)
        ON DELETE CASCADE;


-- Clés étrangères Promotion -> Produit
ALTER TABLE promotion
    ADD CONSTRAINT FK_PromotionProduit
        FOREIGN KEY (PMT_PRODUIT_ID)
        REFERENCES produit(PRO_ID);


-- Clés étrangères Commentaire -> Produit
ALTER TABLE commentaire
    ADD CONSTRAINT FK_CommentaireProduit
        FOREIGN KEY (COM_PRODUIT_ID)
        REFERENCES produit(PRO_ID)
        ON DELETE CASCADE;


-- Clés étrangères Commentaire -> Client
ALTER TABLE commentaire
    ADD CONSTRAINT FK_CommentaireClient
        FOREIGN KEY (COM_CLIENT_ID)
        REFERENCES client(CLI_ID)
        ON DELETE CASCADE;
